Update azurepipeline.yml for Azure Pipelines

diff --git a/Deployment_Virtual_Machine/Pipelines/azurepipeline.yml b/Deployment_Virtual_Machine/Pipelines/azurepipeline.yml
--- a/Deployment_Virtual_Machine/Pipelines/azurepipeline.yml
+++ b/Deployment_Virtual_Machine/Pipelines/azurepipeline.yml
@@ -39,38 +39,6 @@ variables:
 - group: Dev-Secrets
 
 stages:
-
-- stage: Terraform_init_${{ parameters.Environment }}
-  displayName: init ${{ parameters.Environment }}
-  jobs:
-  - job: Terraform_init
-    displayName: Plan Terraform
-    pool:
-      vmImage: ubuntu-latest
-    steps:
-
-    # Terraform init
-    - task: AzureCLI@1
-      displayName: "Terraform Init"
-      inputs:
-       azureSubscription: $"(AzureSubscriptionServiceConnectionName)"
-       scriptLocation: 'inlineScript'
-       inlineScript: |
-        set -eux  # fail on error
-        subscriptionId=$(az account show --query id -o tsv)
-        echo "Terraform Init"
-        terraform init -input=false \
-        -backend-config="resource_group_name=$"(tf-resourcegroup)" \
-        -backend-config="storage_account_name=$"(tf-storageaccount)" \
-        -backend-config="container_name=$"(tf-containername)" \
-        -backend-config="key=$"(tf-statekey)" \
-        -backend-config="subscription_id=$(subscription-id)" \
-        -backend-config="tenant_id=$(tenant-id)" \
-        -backend-config="client_id=$(spn-id)" \
-        -backend-config="client_secret=$(spn-secret)"
-       workingDirectory: ${{ parameters.TerraformDirectory }}
-       addSpnToEnvironment: true
-
 - stage: Terraform_Plan_${{ parameters.Environment }}
   displayName: Plan ${{ parameters.Environment }}
   jobs:
@@ -81,6 +49,29 @@ stages:
     pool:
       vmImage: ubuntu-latest
     steps:
+
+tages:
+- stage: Terraform_Plan_${{ parameters.Environment }}
+  displayName: Plan ${{ parameters.Environment }}
+  jobs:
+  - job: Terraform_Plan
+    displayName: Plan Terraform
+    # Avoid concurrent Terraform runs on PRs, which would result in failures due to exclusive lock on remote state file.
+    # condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), variables['RUN_FLAG_TERRAFORM']))
+    pool:
+      vmImage: ubuntu-latest
+    steps:
+
+    - template: ./terraform-init-template.yml
+      parameters:
+        Environment: ${{ parameters.Environment }}
+        TerraformDirectory: ${{ parameters.TerraformDirectory }}
+        provisionStorage: ${{ parameters.provisionStorage }}
+        AzureSubscription: $(AzureSubscriptionServiceConnectionName)
+        location: ${{ parameters.location }}
+        locationshortprefix: ${{ parameters.locationshortprefix }}
+        TerraformVersion: ${{ parameters.TerraformVersion }}
+
     - bash: |
         set -eu
         export ARM_CLIENT_SECRET=$(spn-secret)
@@ -89,18 +80,37 @@ stages:
         echo "list of files avalibale in the current directory"
         ls -la
         terraform plan -input=false -out=tfplan -var-file=global_var.tfvars -var-file=${{ parameters.Environment }}_var.tfvars -var 'Environment=${{ parameters.Environment }}' -var 'locationshortprefix=${{ parameters.locationshortprefix  }}' -var 'rg_location=${{ parameters.location }}'
+        # terraform plan \
+        # -input=false \
+        # -var 'Environment=${{ parameters.Environment }}' \
+        # -var 'locationshortprefix=${{ parameters.locationshortprefix  }}' \
+        # -var 'rg_location=${{ parameters.location }}' \
+        # -var-file=global_var.tfvars -var-file=${{ parameters.Environment }}_var.tfvars \
+        # -out="tfplan"
       workingDirectory: ${{ parameters.TerraformDirectory }}
       env:
         ARM_SUBSCRIPTION_ID: $(subscription-id)
         ARM_CLIENT_ID:       $(spn-id)
         ARM_CLIENT_SECRET:   $(spn-secret)
         ARM_TENANT_ID:       $(tenant-id)
+
+    - bash: |
+        # Save a human-friendly version of the plan with passwords hidden
+        terraform show -no-color tfplan > plan.txt
+        # Remove terraform plan from published artifacts, as it contains clear-text secrets
+        rm tfplan
+        # Resource providers can be > 100MB large, we don't want them in the published artifacts.
+        rm -r .terraform
+      displayName: Save plan text
+      workingDirectory: ${{ parameters.TerraformDirectory }}
+
     - bash: |
         echo "set current workig directory"
         cd $(System.DefaultWorkingDirectory)
         echo "current working directory"
         pwd
       displayName: setting artifacts path to root
+
     - task: PublishPipelineArtifact@1
       displayName: Publish plan artifact
       inputs:
@@ -139,8 +149,44 @@ stages:
               locationshortprefix: ${{ parameters.locationshortprefix }}
               TerraformVersion: ${{ parameters.TerraformVersion }}
 
+          # As the Terraform extension plan task doesn't support -detailed-exitcode
+          # (to check if any changes are present), we define an equivalent bash
+          # task instead.
           - bash: |
               set -eu
+              export ARM_CLIENT_SECRET=$(spn-secret)
+              # terraform plan -detailed-exitcode exit codes:
+              # 0 - Succeeded, diff is empty (no changes)
+              # 1 - Errored
+              # 2 - Succeeded, there is a diff
+              # >2 - unexpected, crash or bug
+              if terraform plan -detailed-exitcode -input=false -out=tfplan -var-file=global_var.tfvars -var-file=${{ parameters.Environment }}_var.tfvars -var 'Environment=${{ parameters.Environment }}' -var 'locationshortprefix=${{ parameters.locationshortprefix  }}' -var 'rg_location=${{ parameters.location }}'; then
+                echo "Terraform succeeded with no changes"
+                # NB terraform apply should still be run, e.g. if new outputs have been created
+              else
+                terraform_exitcode=$?
+                if [ $terraform_exitcode -eq 2 ]; then
+                  echo "Terraform succeeded with updates"
+                else
+                  echo "ERROR: terraform exited with code $terraform_exitcode"
+                  exit 1
+                fi
+              fi
+            displayName: Terraform plan 
+            workingDirectory: terraform_resources/${{ parameters.TerraformDirectory }}
+            env:
+              ARM_SUBSCRIPTION_ID: $(subscription-id)
+              ARM_CLIENT_ID:       $(spn-id)
+              ARM_CLIENT_SECRET:   $(spn-secret)
+              ARM_TENANT_ID:       $(tenant-id)
+          - bash: |
+              set -eux  # ensure pipeline stops if terraform fails or diff reports a difference
+              terraform show -no-color tfplan > newplan.txt
+              diff -u plan.txt newplan.txt
+            workingDirectory: terraform_resources/${{ parameters.TerraformDirectory }}
+            displayName: Check unchanged plan
+          - bash: |
+              set -eux
               terraform apply -input=false -auto-approve tfplan
             displayName: Terraform apply
             workingDirectory: terraform_resources/${{ parameters.TerraformDirectory }}
